### ISSUE TITLE
Parition field

### ISSUE THREAD

**Issue by pullyvan** [researchapps/job-maker#14]
Hello,

Many thanks for your incredible work, everything seems to work but it seems that the web interface do not find the partition, is it something special I need to do ?

![image](https://user-images.githubusercontent.com/19305007/87302398-9c8fb100-c511-11ea-9425-23092a9f3a36.png)

Best regards,
Pullyvan

**Comment by vsoch** [comment]
You entered a cluster that does not exist, compute-cluster, so naturally there are not partitions. If you want to set it up for your own institution there are scripts and instructions so you can do this. The live version represents a freeze in time of Stanford a few years ago.

**Comment by pullyvan** [comment]
Many thanks again, I was able to fix this with your help

Great work !!
Pullyvan
