### ISSUE TITLE
Questions from a center with a similar tool

### ISSUE THREAD

**Issue by dtrudg** [researchapps/job-maker#9]
Came across your job-maker today, while looking for such things :-) We have a similar tool here that I developed in ember about 2 1/2 years ago now, integrated into our HPC web portal. Unfortunately it's not open-source (yet). It is, however, very similar with some differences being:

* You can add serial/parallel command groups to the script in the web, rather than call a single script/program.
* It allows selection of modules on the cluster from a modal window
* Can submit directly into the batch system
* Script updates on the fly as form edits are made
* It does not support reading the cluster configuration nicely - horrible hard-coded stuff ahoy.

I wondered if you are developing your tool further? The thing we have is the only ember app across all of our projects - and ember is overly complex for it. If this job-maker is an ongoing project, it'd be something that we might consider as a possible future replacement for our code, and something we could contribute to.

![capture](https://user-images.githubusercontent.com/4522799/30084725-27bea964-9259-11e7-8210-f271f8999165.JPG)

**Comment by vsoch** [comment]
hey @dctrud, this sounds like an awesome idea! I agree completely that ember isn't as well known (or at least now, Vue.js is very popular). I would love to combine the two tools, and further, I'd even suggest we look critically across the general tools we have, the needs of the users, and make development a group effort. Do you want to join researchapps and start hacking away? I can also, with some guidance about additions, give a first go at adding specific needs for your center. I would say we should strive for the following:

- general tools for HPC groups (admins and users) 
- they should be customizable by the user
- each should have a good docs base
- we should try to build some community initiative into it - I created researchapps for this purpose but it's mostly been me hacking around stuff :)
- to the best of our ability, if possible, provide containers for things.
- (knowing yours and others needs) have clear instructions, etc for private deployment

What

**Comment by dtrudg** [comment]
Hi. This particular thing (slurm script creator) will likely be a project for a new member as they join our team - so it won't be me coding, and it isn't going to be an immediate thing. Just anxious for them to not re-invent the wheel (again), and hopefully contribute to something that is alive outside of our small team.

The researchapps idea is a good one. We have a bunch of things that are of at least some interest to others, and are looking to open-source bits over the next year or so. Open-source release isn't something that's routine here, so it will take time - but those in charge are behind it.

**Comment by vsoch** [comment]
okay great! Ping on here (you or the new member) when the time is right.

**Comment by dtrudg** [comment]
Not a ping to jump in yet, but just rediscovered a git repo from 2 years ago of the standalone tool before we integrated it into our portal. https://git.biohpc.swmed.edu/david.trudgian/ember_sbatch

If you want to look it's just a clone and open index.html - modules, partitions etc. are nasty hard coded things before the portal integration (after which they pull them from json REST endpoints).

**Comment by vsoch** [comment]
Closing this issue, you've moved on from that position. Thanks for the ping!

**Comment by dtrudg** [comment]
I'm actually back and maintaining the portal where it's used again... but work on a scripted tool isn't a high priority at present. Cheers.

**Comment by vsoch** [comment]
Cheers!
